import { Game } from './types';

// Initial game library with mix of classic and AI-generated style games
export const initialGames: Game[] = [
  // Action Games
  {
    id: 'neon-blaster',
    title: 'Neon Blaster',
    description: 'Blast through waves of enemies in this fast-paced neon shooter',
    category: 'action',
    tags: ['shooter', 'neon', 'arcade', 'fast-paced'],
    thumbnail: '/games/neon-blaster/thumbnail.jpg',
    gameUrl: '/games/neon-blaster/index.html',
    featured: true,
    rating: 4.8,
    plays: 15420,
    controls: 'WASD to move, Mouse to aim, Click to shoot',
    createdAt: '2024-01-15'
  },
  {
    id: 'cyber-runner',
    title: 'Cyber Runner',
    description: 'Run, jump, and slide through a cyberpunk cityscape',
    category: 'action',
    tags: ['runner', 'cyberpunk', 'endless'],
    thumbnail: '/games/cyber-runner/thumbnail.jpg',
    gameUrl: '/games/cyber-runner/index.html',
    new: true,
    rating: 4.6,
    plays: 8932,
    controls: 'Space to jump, Down to slide',
    createdAt: '2024-02-01'
  },
  {
    id: 'zombie-slayer',
    title: 'Zombie Slayer',
    description: 'Survive the zombie apocalypse with your arsenal of weapons',
    category: 'action',
    tags: ['zombie', 'survival', 'shooter'],
    thumbnail: '/games/zombie-slayer/thumbnail.jpg',
    gameUrl: '/games/zombie-slayer/index.html',
    rating: 4.5,
    plays: 22100,
    controls: 'WASD to move, Mouse to aim, Click to shoot',
    createdAt: '2024-01-10'
  },

  // Adventure Games
  {
    id: 'lost-temple',
    title: 'Lost Temple',
    description: 'Explore an ancient temple full of traps and treasures',
    category: 'adventure',
    tags: ['exploration', 'puzzle', 'ancient'],
    thumbnail: '/games/lost-temple/thumbnail.jpg',
    gameUrl: '/games/lost-temple/index.html',
    featured: true,
    rating: 4.9,
    plays: 31200,
    controls: 'Arrow keys to move, Space to interact',
    createdAt: '2024-01-05'
  },
  {
    id: 'space-explorer',
    title: 'Space Explorer',
    description: 'Travel through the galaxy and discover new planets',
    category: 'adventure',
    tags: ['space', 'sci-fi', 'exploration'],
    thumbnail: '/games/space-explorer/thumbnail.jpg',
    gameUrl: '/games/space-explorer/index.html',
    new: true,
    rating: 4.7,
    plays: 12400,
    controls: 'WASD to fly, Mouse to look around',
    createdAt: '2024-02-10'
  },
  {
    id: 'dragon-quest',
    title: 'Dragon Quest',
    description: 'Embark on an epic quest to slay the ancient dragon',
    category: 'adventure',
    tags: ['fantasy', 'dragon', 'epic'],
    thumbnail: '/games/dragon-quest/thumbnail.jpg',
    gameUrl: '/games/dragon-quest/index.html',
    rating: 4.8,
    plays: 28900,
    controls: 'WASD to move, J to attack, K to special',
    createdAt: '2024-01-20'
  },

  // Puzzle Games
  {
    id: 'mind-maze',
    title: 'Mind Maze',
    description: 'Navigate through complex labyrinths using logic',
    category: 'puzzle',
    tags: ['maze', 'logic', 'brain-teaser'],
    thumbnail: '/games/mind-maze/thumbnail.jpg',
    gameUrl: '/games/mind-maze/index.html',
    featured: true,
    rating: 4.6,
    plays: 19800,
    controls: 'Arrow keys to move',
    createdAt: '2024-01-08'
  },
  {
    id: 'color-match',
    title: 'Color Match',
    description: 'Match colors and patterns in this addictive puzzle game',
    category: 'puzzle',
    tags: ['color', 'match', 'casual'],
    thumbnail: '/games/color-match/thumbnail.jpg',
    gameUrl: '/games/color-match/index.html',
    new: true,
    rating: 4.4,
    plays: 45000,
    controls: 'Click to select and match',
    createdAt: '2024-02-05'
  },
  {
    id: 'tower-blocks',
    title: 'Tower Blocks',
    description: 'Stack blocks as high as you can without toppling',
    category: 'puzzle',
    tags: ['stacking', 'physics', 'challenging'],
    thumbnail: '/games/tower-blocks/thumbnail.jpg',
    gameUrl: '/games/tower-blocks/index.html',
    rating: 4.3,
    plays: 52300,
    controls: 'Click to drop blocks',
    createdAt: '2024-01-12'
  },

  // Racing Games
  {
    id: 'speed-demon',
    title: 'Speed Demon',
    description: 'Race at breakneck speeds through neon-lit tracks',
    category: 'racing',
    tags: ['fast', 'neon', 'drifting'],
    thumbnail: '/games/speed-demon/thumbnail.jpg',
    gameUrl: '/games/speed-demon/index.html',
    featured: true,
    rating: 4.7,
    plays: 34500,
    controls: 'Arrow keys to steer, Space to boost',
    createdAt: '2024-01-18'
  },
  {
    id: 'drift-king',
    title: 'Drift King',
    description: 'Master the art of drifting on challenging circuits',
    category: 'racing',
    tags: ['drifting', 'cars', 'skill'],
    thumbnail: '/games/drift-king/thumbnail.jpg',
    gameUrl: '/games/drift-king/index.html',
    new: true,
    rating: 4.5,
    plays: 18700,
    controls: 'Arrow keys, Space for handbrake',
    createdAt: '2024-02-08'
  },
  {
    id: 'offroad-madness',
    title: 'Offroad Madness',
    description: 'Conquer rugged terrain in powerful offroad vehicles',
    category: 'racing',
    tags: ['offroad', 'trucks', 'terrain'],
    thumbnail: '/games/offroad-madness/thumbnail.jpg',
    gameUrl: '/games/offroad-madness/index.html',
    rating: 4.4,
    plays: 12400,
    controls: 'WASD to drive, Space for nitro',
    createdAt: '2024-01-25'
  },

  // Sports Games
  {
    id: 'basketball-stars',
    title: 'Basketball Stars',
    description: 'Show off your basketball skills in 1v1 matches',
    category: 'sports',
    tags: ['basketball', '1v1', 'competitive'],
    thumbnail: '/games/basketball-stars/thumbnail.jpg',
    gameUrl: '/games/basketball-stars/index.html',
    rating: 4.6,
    plays: 41200,
    controls: 'WASD to move, Space to shoot',
    createdAt: '2024-01-14'
  },
  {
    id: 'soccer-champions',
    title: 'Soccer Champions',
    description: 'Lead your team to victory in intense soccer matches',
    category: 'sports',
    tags: ['soccer', 'team', 'goal'],
    thumbnail: '/games/soccer-champions/thumbnail.jpg',
    gameUrl: '/games/soccer-champions/index.html',
    new: true,
    rating: 4.5,
    plays: 28900,
    controls: 'WASD to move, Space to kick',
    createdAt: '2024-02-12'
  },
  {
    id: 'tennis-pro',
    title: 'Tennis Pro',
    description: 'Serve, volley, and ace your way to the championship',
    category: 'sports',
    tags: ['tennis', 'racket', 'arcade'],
    thumbnail: '/games/tennis-pro/thumbnail.jpg',
    gameUrl: '/games/tennis-pro/index.html',
    rating: 4.3,
    plays: 15600,
    controls: 'Mouse to aim, Click to swing',
    createdAt: '2024-01-22'
  },

  // Strategy Games
  {
    id: 'kingdom-defense',
    title: 'Kingdom Defense',
    description: 'Defend your kingdom from waves of enemies',
    category: 'strategy',
    tags: ['tower-defense', 'medieval', 'planning'],
    thumbnail: '/games/kingdom-defense/thumbnail.jpg',
    gameUrl: '/games/kingdom-defense/index.html',
    featured: true,
    rating: 4.8,
    plays: 38900,
    controls: 'Click to place towers',
    createdAt: '2024-01-03'
  },
  {
    id: 'empire-builder',
    title: 'Empire Builder',
    description: 'Build and manage your own thriving empire',
    category: 'strategy',
    tags: ['building', 'management', 'city'],
    thumbnail: '/games/empire-builder/thumbnail.jpg',
    gameUrl: '/games/empire-builder/index.html',
    rating: 4.6,
    plays: 23400,
    controls: 'Click to build and upgrade',
    createdAt: '2024-01-16'
  },
  {
    id: 'chess-master',
    title: 'Chess Master',
    description: 'Challenge AI opponents in classic chess matches',
    category: 'strategy',
    tags: ['chess', 'classic', 'ai'],
    thumbnail: '/games/chess-master/thumbnail.jpg',
    gameUrl: '/games/chess-master/index.html',
    new: true,
    rating: 4.7,
    plays: 45600,
    controls: 'Click to move pieces',
    createdAt: '2024-02-03'
  },

  // Horror Games
  {
    id: 'haunted-house',
    title: 'Haunted House',
    description: 'Escape a terrifying haunted house filled with ghosts',
    category: 'horror',
    tags: ['scary', 'ghosts', 'escape'],
    thumbnail: '/games/haunted-house/thumbnail.jpg',
    gameUrl: '/games/haunted-house/index.html',
    featured: true,
    rating: 4.7,
    plays: 27800,
    controls: 'WASD to move, Space to interact',
    createdAt: '2024-01-20'
  },
  {
    id: 'dark-forest',
    title: 'Dark Forest',
    description: 'Survive the horrors lurking in the dark forest',
    category: 'horror',
    tags: ['forest', 'survival', 'monsters'],
    thumbnail: '/games/dark-forest/thumbnail.jpg',
    gameUrl: '/games/dark-forest/index.html',
    new: true,
    rating: 4.5,
    plays: 19200,
    controls: 'WASD to move, Shift to run',
    createdAt: '2024-02-07'
  },
  {
    id: 'nightmare-crew',
    title: 'Nightmare Crew',
    description: 'Face your worst nightmares in this psychological horror',
    category: 'horror',
    tags: ['nightmare', 'psychological', 'tense'],
    thumbnail: '/games/nightmare-crew/thumbnail.jpg',
    gameUrl: '/games/nightmare-crew/index.html',
    rating: 4.6,
    plays: 14500,
    controls: 'WASD to move, E to interact',
    createdAt: '2024-01-28'
  },

  // Mystery Games
  {
    id: 'detective-case',
    title: 'Detective Case',
    description: 'Solve mysterious crimes as a brilliant detective',
    category: 'mystery',
    tags: ['detective', 'crime', 'investigation'],
    thumbnail: '/games/detective-case/thumbnail.jpg',
    gameUrl: '/games/detective-case/index.html',
    featured: true,
    rating: 4.9,
    plays: 35600,
    controls: 'Click to examine, drag to collect evidence',
    createdAt: '2024-01-07'
  },
  {
    id: 'escape-room',
    title: 'Escape Room',
    description: 'Find clues and escape from locked rooms',
    category: 'mystery',
    tags: ['escape', 'puzzle', 'clues'],
    thumbnail: '/games/escape-room/thumbnail.jpg',
    gameUrl: '/games/escape-room/index.html',
    new: true,
    rating: 4.8,
    plays: 42300,
    controls: 'Click to interact with objects',
    createdAt: '2024-02-09'
  },
  {
    id: 'secret-society',
    title: 'Secret Society',
    description: 'Uncover the secrets of an ancient hidden society',
    category: 'mystery',
    tags: ['secrets', 'conspiracy', 'intrigue'],
    thumbnail: '/games/secret-society/thumbnail.jpg',
    gameUrl: '/games/secret-society/index.html',
    rating: 4.6,
    plays: 21800,
    controls: 'WASD to move, E to talk',
    createdAt: '2024-01-24'
  },

  // Arcade Games
  {
    id: 'retro-snake',
    title: 'Retro Snake',
    description: 'Classic snake game with neon graphics',
    category: 'arcade',
    tags: ['retro', 'classic', 'snake'],
    thumbnail: '/games/retro-snake/thumbnail.jpg',
    gameUrl: '/games/retro-snake/index.html',
    rating: 4.4,
    plays: 67800,
    controls: 'Arrow keys to move',
    createdAt: '2024-01-02'
  },
  {
    id: 'space-invaders-x',
    title: 'Space Invaders X',
    description: 'Defend Earth from waves of alien invaders',
    category: 'arcade',
    tags: ['space', 'shooter', 'classic'],
    thumbnail: '/games/space-invaders-x/thumbnail.jpg',
    gameUrl: '/games/space-invaders-x/index.html',
    new: true,
    rating: 4.5,
    plays: 38900,
    controls: 'Arrow keys to move, Space to shoot',
    createdAt: '2024-02-11'
  },
  {
    id: 'tetris-supreme',
    title: 'Tetris Supreme',
    description: 'Stack blocks and clear lines in this ultimate Tetris',
    category: 'arcade',
    tags: ['tetris', 'blocks', 'classic'],
    thumbnail: '/games/tetris-supreme/thumbnail.jpg',
    gameUrl: '/games/tetris-supreme/index.html',
    rating: 4.7,
    plays: 89200,
    controls: 'Arrow keys to move and rotate',
    createdAt: '2024-01-11'
  },

  // RPG Games
  {
    id: 'dragon-warrior',
    title: 'Dragon Warrior',
    description: 'Embark on an epic RPG adventure',
    category: 'rpg',
    tags: ['fantasy', 'adventure', 'combat'],
    thumbnail: '/games/dragon-warrior/thumbnail.jpg',
    gameUrl: '/games/dragon-warrior/index.html',
    featured: true,
    rating: 4.9,
    plays: 56700,
    controls: 'WASD to move, J to attack, K for magic',
    createdAt: '2024-01-04'
  },
  {
    id: 'pixel-quest',
    title: 'Pixel Quest',
    description: 'Explore a pixel art world filled with adventures',
    category: 'rpg',
    tags: ['pixel', 'retro', 'adventure'],
    thumbnail: '/games/pixel-quest/thumbnail.jpg',
    gameUrl: '/games/pixel-quest/index.html',
    new: true,
    rating: 4.6,
    plays: 31200,
    controls: 'Arrow keys to move, Space to interact',
    createdAt: '2024-02-06'
  },
  {
    id: 'dungeon-crawler',
    title: 'Dungeon Crawler',
    description: 'Delve deep into dungeons and battle monsters',
    category: 'rpg',
    tags: ['dungeon', 'monsters', 'loot'],
    thumbnail: '/games/dungeon-crawler/thumbnail.jpg',
    gameUrl: '/games/dungeon-crawler/index.html',
    rating: 4.7,
    plays: 29800,
    controls: 'WASD to move, Mouse to attack',
    createdAt: '2024-01-19'
  },

  // Simulation Games
  {
    id: 'city-builder',
    title: 'City Builder',
    description: 'Build and manage your own bustling city',
    category: 'simulation',
    tags: ['city', 'building', 'management'],
    thumbnail: '/games/city-builder/thumbnail.jpg',
    gameUrl: '/games/city-builder/index.html',
    rating: 4.5,
    plays: 23400,
    controls: 'Click to place buildings',
    createdAt: '2024-01-13'
  },
  {
    id: 'flight-sim',
    title: 'Flight Simulator',
    description: 'Experience realistic flight in various aircraft',
    category: 'simulation',
    tags: ['flight', 'planes', 'realistic'],
    thumbnail: '/games/flight-sim/thumbnail.jpg',
    gameUrl: '/games/flight-sim/index.html',
    new: true,
    rating: 4.8,
    plays: 18900,
    controls: 'WASD for pitch/roll, QE for yaw',
    createdAt: '2024-02-04'
  },
  {
    id: 'farming-life',
    title: 'Farming Life',
    description: 'Run your own farm and become a successful farmer',
    category: 'simulation',
    tags: ['farming', 'relaxing', 'life'],
    thumbnail: '/games/farming-life/thumbnail.jpg',
    gameUrl: '/games/farming-life/index.html',
    rating: 4.4,
    plays: 15600,
    controls: 'WASD to move, E to interact',
    createdAt: '2024-01-26'
  },

  // Casual Games
  {
    id: 'bubble-shooter',
    title: 'Bubble Shooter',
    description: 'Pop colorful bubbles in this relaxing game',
    category: 'casual',
    tags: ['bubbles', 'relaxing', 'pop'],
    thumbnail: '/games/bubble-shooter/thumbnail.jpg',
    gameUrl: '/games/bubble-shooter/index.html',
    rating: 4.5,
    plays: 78900,
    controls: 'Mouse to aim, Click to shoot',
    createdAt: '2024-01-06'
  },
  {
    id: 'candy-crush',
    title: 'Candy Crush',
    description: 'Match candies and solve sweet puzzles',
    category: 'casual',
    tags: ['candy', 'match-3', 'sweet'],
    thumbnail: '/games/candy-crush/thumbnail.jpg',
    gameUrl: '/games/candy-crush/index.html',
    new: true,
    rating: 4.6,
    plays: 92100,
    controls: 'Click to match 3 or more',
    createdAt: '2024-02-13'
  },
  {
    id: 'pet-paradise',
    title: 'Pet Paradise',
    description: 'Take care of adorable virtual pets',
    category: 'casual',
    tags: ['pets', 'cute', 'care'],
    thumbnail: '/games/pet-paradise/thumbnail.jpg',
    gameUrl: '/games/pet-paradise/index.html',
    rating: 4.3,
    plays: 34500,
    controls: 'Click to feed and play',
    createdAt: '2024-01-27'
  },

  // 2D Games
  {
    id: '2d-platformer',
    title: '2D Platformer Pro',
    description: 'Jump and run through colorful 2D worlds',
    category: '2d',
    tags: ['platformer', '2d', 'jump'],
    thumbnail: '/games/2d-platformer/thumbnail.jpg',
    gameUrl: '/games/2d-platformer/index.html',
    rating: 4.6,
    plays: 45600,
    controls: 'Arrow keys to move, Space to jump',
    createdAt: '2024-01-09'
  },
  {
    id: 'side-scroller',
    title: 'Side Scroller Saga',
    description: 'Epic side-scrolling adventure awaits',
    category: '2d',
    tags: ['side-scroll', 'action', 'adventure'],
    thumbnail: '/games/side-scroller/thumbnail.jpg',
    gameUrl: '/games/side-scroller/index.html',
    new: true,
    rating: 4.5,
    plays: 28700,
    controls: 'WASD to move, J to attack',
    createdAt: '2024-02-02'
  },
  {
    id: 'pixel-art-world',
    title: 'Pixel Art World',
    description: 'Explore a beautiful pixel art universe',
    category: '2d',
    tags: ['pixel', 'art', 'exploration'],
    thumbnail: '/games/pixel-art-world/thumbnail.jpg',
    gameUrl: '/games/pixel-art-world/index.html',
    rating: 4.7,
    plays: 21300,
    controls: 'Arrow keys to explore',
    createdAt: '2024-01-21'
  },

  // 3D Games
  {
    id: '3d-explorer',
    title: '3D Explorer',
    description: 'Explore fully 3D rendered worlds',
    category: '3d',
    tags: ['3d', 'exploration', 'immersive'],
    thumbnail: '/games/3d-explorer/thumbnail.jpg',
    gameUrl: '/games/3d-explorer/index.html',
    featured: true,
    rating: 4.8,
    plays: 34200,
    controls: 'WASD to move, Mouse to look',
    createdAt: '2024-01-01'
  },
  {
    id: '3d-racing',
    title: '3D Racing Extreme',
    description: 'High-speed 3D racing with stunning graphics',
    category: '3d',
    tags: ['3d', 'racing', 'speed'],
    thumbnail: '/games/3d-racing/thumbnail.jpg',
    gameUrl: '/games/3d-racing/index.html',
    new: true,
    rating: 4.7,
    plays: 27800,
    controls: 'Arrow keys to drive',
    createdAt: '2024-02-14'
  },
  {
    id: '3d-shooter',
    title: '3D Shooter Arena',
    description: 'First-person 3D shooter combat',
    category: '3d',
    tags: ['3d', 'fps', 'shooter'],
    thumbnail: '/games/3d-shooter/thumbnail.jpg',
    gameUrl: '/games/3d-shooter/index.html',
    rating: 4.6,
    plays: 35600,
    controls: 'WASD to move, Mouse to aim and shoot',
    createdAt: '2024-01-17'
  },

  // Multiplayer Games
  {
    id: 'multiplayer-arena',
    title: 'Multiplayer Arena',
    description: 'Battle players from around the world',
    category: 'multiplayer',
    tags: ['multiplayer', 'battle', 'online'],
    thumbnail: '/games/multiplayer-arena/thumbnail.jpg',
    gameUrl: '/games/multiplayer-arena/index.html',
    featured: true,
    rating: 4.8,
    plays: 67800,
    controls: 'WASD to move, Mouse to aim',
    createdAt: '2024-01-05'
  },
  {
    id: 'battle-royale',
    title: 'Mini Battle Royale',
    description: 'Last player standing in fast-paced matches',
    category: 'multiplayer',
    tags: ['battle-royale', 'survival', 'fight'],
    thumbnail: '/games/battle-royale/thumbnail.jpg',
    gameUrl: '/games/battle-royale/index.html',
    new: true,
    rating: 4.7,
    plays: 89400,
    controls: 'WASD to move, Mouse to aim',
    createdAt: '2024-02-15'
  },
  {
    id: 'coop-adventure',
    title: 'Co-op Adventure',
    description: 'Team up with friends for epic adventures',
    category: 'multiplayer',
    tags: ['co-op', 'team', 'adventure'],
    thumbnail: '/games/coop-adventure/thumbnail.jpg',
    gameUrl: '/games/coop-adventure/index.html',
    rating: 4.6,
    plays: 34500,
    controls: 'WASD to move, E to interact',
    createdAt: '2024-01-29'
  },
];

// Categories with their descriptions
export const categoryDescriptions: Record<string, string> = {
  action: 'High-energy games that test your reflexes and combat skills',
  adventure: 'Explore vast worlds and embark on epic quests',
  puzzle: 'Challenge your brain with logic and problem-solving',
  racing: 'Feel the rush of speed in thrilling races',
  sports: 'Compete in your favorite sports games',
  strategy: 'Plan, think ahead, and outsmart your opponents',
  horror: 'Face your fears in spine-chilling horror games',
  mystery: 'Uncover secrets and solve intriguing puzzles',
  arcade: 'Classic arcade action that never gets old',
  rpg: 'Level up your character in immersive role-playing games',
  simulation: 'Experience realistic scenarios and management',
  casual: 'Relaxing games perfect for any break',
  '2d': 'Beautiful 2D games with stunning pixel art',
  '3d': 'Immersive 3D worlds with realistic graphics',
  multiplayer: 'Play with friends and compete globally',
};
